name: Formatter

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Format
        run: markdownlint-cli --fix '**/*.md'

      - name: Commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Local branch and remote branch are inconsistent. Pushing changes..."
            git commit -m "Auto-format code"
            git push
          else
            echo "Local branch and remote branch are consistent. No action needed."
          fi
